"""
Tool registry that bridges FastMCP servers to LangChain-compatible tools.

Each MCP server exposes a FastMCP instance. This registry discovers tools
from those instances at runtime and wraps them as LangChain StructuredTools
so LangGraph agents can invoke them through a standardised interface.

Production improvements over the previous implementation:
- Uses FastMCP 3.x native API (list_tools / call_tool) — no manual JSON schemas
- anyOf/Union type schemas (from int | None annotations) are resolved correctly
- Tool descriptions come from Python docstrings — single source of truth
- Error messages are surfaced as tool results rather than raised exceptions
"""

from typing import Any, Optional

from langchain_core.tools import StructuredTool
from pydantic import BaseModel, Field, create_model

from src.mcp_servers.filesystem_server import mcp as fs_mcp
from src.mcp_servers.shell_server import mcp as shell_mcp
from src.mcp_servers.git_server import mcp as git_mcp
from src.mcp_servers.web_server import mcp as web_mcp
from src.mcp_servers.memory_server import mcp as mem_mcp
from src.mcp_servers.planner_server import mcp as planner_mcp
from src.mcp_servers.github_server import mcp as github_mcp
from src.mcp_servers.jira_server import mcp as jira_mcp
from src.mcp_servers.finance_server import mcp as finance_mcp


# ── Schema conversion ─────────────────────────────────────────────

JSON_TYPE_MAP = {
    "string": str,
    "integer": int,
    "number": float,
    "boolean": bool,
    "array": list,
    "object": dict,
}


def _resolve_type(prop_schema: dict) -> type:
    """Resolve a JSON Schema property definition to a Python type.

    Handles both simple {"type": "string"} and anyOf/Union schemas
    generated by FastMCP for Optional parameters (e.g. int | None).
    """
    type_str = prop_schema.get("type")
    if type_str:
        return JSON_TYPE_MAP.get(type_str, str)

    # Handle anyOf for Union types (e.g. int | None → anyOf: [{type: integer}, {type: null}])
    for sub in prop_schema.get("anyOf", []):
        if sub.get("type") != "null":
            return JSON_TYPE_MAP.get(sub.get("type", "string"), str)

    return str


def _schema_to_pydantic(tool_name: str, schema: dict) -> type[BaseModel]:
    """Convert a JSON Schema from a FastMCP tool into a Pydantic model.

    Optional parameters are represented with concrete types + sentinel defaults
    rather than Optional[X] so that Pydantic v2 does NOT emit anyOf in the
    serialised JSON Schema. The Poe API returns HTTP 500 for schemas that
    contain anyOf constructs.
    """
    properties = schema.get("properties", {})
    required = set(schema.get("required", []))
    fields: dict[str, Any] = {}

    for prop_name, prop_schema in properties.items():
        py_type = _resolve_type(prop_schema)
        description = prop_schema.get("description", "")
        default = prop_schema.get("default")

        if prop_name in required:
            fields[prop_name] = (py_type, Field(description=description))
        elif default is not None:
            # Use the concrete type with its default — avoids Optional/anyOf in JSON Schema
            fields[prop_name] = (py_type, Field(default=default, description=description))
        else:
            # No default in schema; use the sentinel value appropriate for the type
            _sentinel: Any = "" if py_type is str else (0 if py_type is int else (0.0 if py_type is float else (False if py_type is bool else None)))
            fields[prop_name] = (py_type, Field(default=_sentinel, description=description))

    model_name = "".join(part.capitalize() for part in tool_name.split("_")) + "Args"
    return create_model(model_name, **fields)


# ── FastMCP → LangChain bridge ────────────────────────────────────

def _make_langchain_tool(tool, mcp_server) -> StructuredTool:
    """Create a LangChain StructuredTool from a FastMCP FunctionTool."""
    schema = tool.parameters or {"type": "object", "properties": {}}
    args_model = _schema_to_pydantic(tool.name, schema)
    tool_name = tool.name
    tool_description = tool.description or ""

    # Names of required parameters so we never strip them even if falsy
    _required = set(schema.get("required", []))

    async def _invoke(**kwargs) -> str:
        # Strip optional params that have their sentinel/None value so FastMCP
        # falls back to the function's own default.
        cleaned = {
            k: v for k, v in kwargs.items()
            if k in _required or v is not None
        }
        result = await mcp_server.call_tool(tool_name, cleaned)
        return result.content[0].text if result.content else "No result"

    return StructuredTool.from_function(
        coroutine=_invoke,
        name=tool_name,
        description=tool_description,
        args_schema=args_model,
        func=lambda **kw: None,
    )


async def _get_tools_for(mcp_server) -> list[StructuredTool]:
    """Discover all tools from a FastMCP server and wrap them for LangChain."""
    tools = await mcp_server.list_tools()
    return [_make_langchain_tool(t, mcp_server) for t in tools]


# ── Per-group getters ─────────────────────────────────────────────

async def get_filesystem_tools() -> list[StructuredTool]:
    return await _get_tools_for(fs_mcp)


# Read-only subset of filesystem tools — safe for agents (like Planner) that must
# read context but must NEVER create or modify files.
_FS_READ_ONLY_NAMES = {"read_file", "list_directory", "search_files", "find_files"}


async def get_filesystem_read_tools() -> list[StructuredTool]:
    """Return only the read-only filesystem tools (no write_file, edit_file)."""
    all_fs = await _get_tools_for(fs_mcp)
    return [t for t in all_fs if t.name in _FS_READ_ONLY_NAMES]


async def get_shell_tools() -> list[StructuredTool]:
    return await _get_tools_for(shell_mcp)


async def get_git_tools() -> list[StructuredTool]:
    return await _get_tools_for(git_mcp)


async def get_web_tools() -> list[StructuredTool]:
    return await _get_tools_for(web_mcp)


async def get_memory_tools() -> list[StructuredTool]:
    return await _get_tools_for(mem_mcp)


async def get_planner_tools() -> list[StructuredTool]:
    return await _get_tools_for(planner_mcp)


async def get_github_tools() -> list[StructuredTool]:
    return await _get_tools_for(github_mcp)


async def get_jira_tools() -> list[StructuredTool]:
    return await _get_tools_for(jira_mcp)


# Finance tool groups — split by analyst persona so each agent only sees the
# tools its prompt budget allows. The grouping mirrors the Tauric TradingAgents
# division of labour (market data / news / fundamentals).
_FINANCE_MARKET_NAMES = {"get_stock_data", "get_indicators"}
_FINANCE_NEWS_NAMES = {"get_news", "get_global_news"}
_FINANCE_FUNDAMENTALS_NAMES = {
    "get_fundamentals", "get_balance_sheet", "get_cashflow", "get_income_statement",
}


async def get_finance_market_tools() -> list[StructuredTool]:
    """Price + technical-indicator tools (Market Analyst, Risk Analyst)."""
    all_finance = await _get_tools_for(finance_mcp)
    return [t for t in all_finance if t.name in _FINANCE_MARKET_NAMES]


async def get_finance_news_tools() -> list[StructuredTool]:
    """News headlines (News Analyst, Social Analyst)."""
    all_finance = await _get_tools_for(finance_mcp)
    return [t for t in all_finance if t.name in _FINANCE_NEWS_NAMES]


async def get_finance_fundamentals_tools() -> list[StructuredTool]:
    """Financial statements + key ratios (Fundamentals Analyst)."""
    all_finance = await _get_tools_for(finance_mcp)
    return [t for t in all_finance if t.name in _FINANCE_FUNDAMENTALS_NAMES]


def get_rag_tools() -> list[StructuredTool]:
    """Return RAG search tools: general rag_search + domain-specific perf_search."""

    # ── Shared helper ──────────────────────────────────────────────────────────

    async def _run_rag_query(
        query: str,
        config_id: Optional[str] = None,
        use_compression: bool = False,
    ) -> str:
        """Resolve a RAG config, run the pipeline, and format citations."""
        from src.db.database import get_session
        from src.db.models import RagConfig as RagConfigModel
        from src.rag.pipeline import RAGConfig, get_pipeline

        session = get_session()
        try:
            if config_id:
                cfg_row = session.query(RagConfigModel).filter_by(id=config_id, is_active=True).first()
            else:
                cfg_row = session.query(RagConfigModel).filter_by(is_active=True).first()
        finally:
            session.close()

        if not cfg_row:
            return "No active RAG knowledge base found. Please configure and ingest documents first."

        cfg = RAGConfig(
            config_id=cfg_row.id,
            name=cfg_row.name,
            embedding_model=cfg_row.embedding_model,
            vector_store=cfg_row.vector_store,
            llm_model=cfg_row.llm_model,
            chunk_size=cfg_row.chunk_size,
            chunk_overlap=cfg_row.chunk_overlap,
            chunk_strategy=cfg_row.chunk_strategy,
            retrieval_strategy=cfg_row.retrieval_strategy,
            top_k=cfg_row.top_k,
            mmr_lambda=cfg_row.mmr_lambda or 0.5,
            multi_query_n=cfg_row.multi_query_n or 3,
            system_prompt=cfg_row.system_prompt,
        )
        pipeline = get_pipeline(cfg)
        if pipeline.chunk_count() == 0:
            return f"RAG knowledge base '{cfg_row.name}' has no ingested documents yet."

        response = await pipeline.query(query, use_compression=use_compression)
        lines = [f"**Knowledge Base Answer** (from '{cfg_row.name}'):\n", response.answer, ""]
        if response.citations:
            lines.append("**Sources:**")
            seen = set()
            for i, c in enumerate(response.citations):
                key = f"{c.source}:{c.chunk_index}"
                if key not in seen:
                    seen.add(key)
                    page_info = f", p.{c.page}" if c.page else ""
                    lines.append(f"[{i + 1}] {c.source}{page_info} (relevance: {c.score:.2f})")
        return "\n".join(lines)

    # ── Tool 1: general rag_search ─────────────────────────────────────────────

    class RagSearchArgs(BaseModel):
        query: str = Field(description="The search query to find relevant information from the knowledge base.")
        config_id: Optional[str] = Field(
            default=None,
            description="RAG config ID to query. If omitted, queries the first active config.",
        )

    async def _rag_search(query: str, config_id: Optional[str] = None) -> str:
        """Query the RAG knowledge base and return cited context."""
        try:
            return await _run_rag_query(query, config_id=config_id, use_compression=False)
        except Exception as e:
            return f"RAG search error: {e}"

    # ── Tool 2: perf_search — always targets Performance Knowledge Base ─────────

    class PerfSearchArgs(BaseModel):
        query: str = Field(
            description=(
                "Performance analysis question. E.g.: "
                "'Why did P99 latency spike in SEA?', "
                "'How to attribute a frame-rate drop?', "
                "'What metrics matter for live stream quality?', "
                "'How to detect A/B experiment novelty effect?'"
            )
        )
        use_compression: bool = Field(
            default=True,
            description=(
                "Apply LLM-based contextual compression to filter out irrelevant "
                "sentences from retrieved chunks before generating the answer. "
                "Reduces hallucination; adds ~1s latency. Default: True."
            ),
        )

    async def _perf_search(query: str, use_compression: bool = True) -> str:
        """
        Query the Performance Analysis Knowledge Base — playbooks, metric taxonomies,
        A/B experiment templates, incident post-mortems, and code review patterns.

        Always use this BEFORE web_search when investigating:
        - Live stream performance anomalies (latency, frame rate, bitrate)
        - A/B experiment methodology or statistical analysis
        - Performance code review patterns (shift-left)
        - Historical incident attribution patterns
        """
        try:
            from src.rag.performance_kb import PERF_KB_CONFIG_ID, seed_performance_kb
            from src.db.database import get_session
            from src.db.models import RagConfig as RagConfigModel
            from src.rag.pipeline import RAGConfig, get_pipeline

            # Auto-seed the KB if it has no documents yet
            session = get_session()
            try:
                cfg_row = session.query(RagConfigModel).filter_by(
                    id=PERF_KB_CONFIG_ID, is_active=True
                ).first()
            finally:
                session.close()

            if cfg_row:
                cfg = RAGConfig(
                    config_id=cfg_row.id,
                    name=cfg_row.name,
                    embedding_model=cfg_row.embedding_model,
                    vector_store=cfg_row.vector_store,
                    llm_model=cfg_row.llm_model,
                    chunk_size=cfg_row.chunk_size,
                    chunk_overlap=cfg_row.chunk_overlap,
                    chunk_strategy=cfg_row.chunk_strategy,
                    retrieval_strategy=cfg_row.retrieval_strategy,
                    top_k=cfg_row.top_k,
                    mmr_lambda=cfg_row.mmr_lambda or 0.5,
                    multi_query_n=cfg_row.multi_query_n or 3,
                    system_prompt=cfg_row.system_prompt,
                )
                pipeline = get_pipeline(cfg)
                if pipeline.chunk_count() == 0:
                    await seed_performance_kb()
                    import asyncio
                    from src.rag.pipeline import evict_pipeline
                    evict_pipeline(PERF_KB_CONFIG_ID)
            else:
                await seed_performance_kb()

            return await _run_rag_query(
                query, config_id=PERF_KB_CONFIG_ID, use_compression=use_compression
            )
        except Exception as e:
            return f"Performance knowledge base search error: {e}"

    return [
        StructuredTool.from_function(
            coroutine=_rag_search,
            name="rag_search",
            description=(
                "Search the internal knowledge base (RAG) for relevant information, documentation, "
                "code patterns, or any ingested content. Always use this tool before web search "
                "when looking for project-specific or domain-specific knowledge."
            ),
            args_schema=RagSearchArgs,
            func=lambda **kw: None,
        ),
        StructuredTool.from_function(
            coroutine=_perf_search,
            name="perf_search",
            description=(
                "Search the Performance Analysis Knowledge Base — contains anomaly attribution "
                "playbooks, A/B experiment templates, live stream metric taxonomies, code "
                "performance review checklists, and incident post-mortems. "
                "ALWAYS call this BEFORE web_search for any performance or live-streaming "
                "analysis question. Returns cited, compressed, domain-specific guidance."
            ),
            args_schema=PerfSearchArgs,
            func=lambda **kw: None,
        ),
    ]


async def get_all_tools() -> dict[str, list[StructuredTool]]:
    """Return all tools grouped by MCP server origin."""
    rag_tools = get_rag_tools()
    # Split into general rag (rag_search) and performance KB (perf_search)
    general_rag = [t for t in rag_tools if t.name == "rag_search"]
    perf_rag = [t for t in rag_tools if t.name == "perf_search"]
    return {
        "filesystem": await get_filesystem_tools(),
        "filesystem_read": await get_filesystem_read_tools(),
        "shell": await get_shell_tools(),
        "git": await get_git_tools(),
        "web": await get_web_tools(),
        "memory": await get_memory_tools(),
        "planner": await get_planner_tools(),
        "github": await get_github_tools(),
        "jira": await get_jira_tools(),
        "rag": general_rag,
        "perf_kb": perf_rag,  # Performance Knowledge Base — domain-specific RAG
        "analytics": get_analytics_tools(),
        "prompt_optimization": get_prompt_optimization_tools(),
        # Finance / trading tool groups (yfinance + stockstats backend).
        "finance_market": await get_finance_market_tools(),
        "finance_news": await get_finance_news_tools(),
        "finance_fundamentals": await get_finance_fundamentals_tools(),
    }


# ── Analytics tools (read-only SQL + regression insights) ─────────────────────

def get_analytics_tools() -> list[StructuredTool]:
    """
    Return analytics tools for the Data Analysis Agent.

    Includes:
      - run_sql: executes read-only SELECT queries against the agent DB
      - get_regression_insights: wrapper around TraceAnalyzer.regression_metric_insights
    """

    # ── Tool 1: run_sql ────────────────────────────────────────────────────────

    class RunSqlArgs(BaseModel):
        sql: str = Field(
            description=(
                "A read-only SELECT SQL query to run against the agent metrics database. "
                "Tables available: regression_results, eval_runs, traces, spans, "
                "golden_test_cases, agents, teams. "
                "Only SELECT statements are allowed — no INSERT, UPDATE, DELETE, or DDL."
            )
        )
        limit: int = Field(
            default=50,
            description="Maximum number of rows to return (default 50, max 200).",
        )

    def _run_sql(sql: str, limit: int = 50) -> str:
        """
        Execute a read-only SQL SELECT query against the agent metrics database.
        Returns results as a formatted table with column headers.

        Safety: only SELECT statements are permitted. Any attempt to run
        INSERT, UPDATE, DELETE, DROP, CREATE, or ALTER will be rejected.
        """
        import re
        # Safety: only allow SELECT
        stripped = sql.strip().upper()
        if not stripped.startswith("SELECT") and not stripped.startswith("WITH"):
            return "ERROR: Only SELECT (and CTEs starting with WITH ... SELECT) are allowed."
        # Block dangerous keywords
        _BLOCKED = re.compile(
            r'\b(INSERT|UPDATE|DELETE|DROP|CREATE|ALTER|TRUNCATE|REPLACE|EXEC|EXECUTE)\b',
            re.IGNORECASE,
        )
        if _BLOCKED.search(sql):
            return "ERROR: Query contains a prohibited keyword (INSERT/UPDATE/DELETE/DROP/etc.)."

        try:
            from src.db.database import get_session
            session = get_session()
            try:
                from sqlalchemy import text
                rows = session.execute(
                    text(sql + (" LIMIT :lim" if "limit" not in sql.lower() else "")),
                    {"lim": min(int(limit), 200)},
                ).fetchall()
                if not rows:
                    return "Query returned 0 rows."

                # Format as markdown table
                cols = list(rows[0]._mapping.keys()) if hasattr(rows[0], "_mapping") else [f"col{i}" for i in range(len(rows[0]))]
                header = " | ".join(str(c) for c in cols)
                sep = " | ".join("---" for _ in cols)
                lines = [f"| {header} |", f"| {sep} |"]
                for row in rows:
                    values = [str(v)[:80] if v is not None else "NULL" for v in row]
                    lines.append("| " + " | ".join(values) + " |")
                return f"Results ({len(rows)} row{'s' if len(rows) != 1 else ''}):\n\n" + "\n".join(lines)
            finally:
                session.close()
        except Exception as e:
            return f"SQL error: {e}"

    # ── Tool 2: get_regression_insights ───────────────────────────────────────

    class RegressionInsightsArgs(BaseModel):
        days: int = Field(
            default=30,
            description="Number of days of regression history to analyse (default 30, max 365).",
        )

    def _get_regression_insights(days: int = 30) -> str:
        """
        Return a structured plain-text summary of regression test performance insights:
        worst-scoring evaluation metrics, most expensive / slowest golden tests,
        agent roles appearing most in failed delegation patterns, and pass rates.
        """
        try:
            from src.tracing.analyzer import TraceAnalyzer
            data = TraceAnalyzer().regression_metric_insights(days=min(int(days), 365))
            summary = data.get("summary", {})
            if summary.get("total_runs", 0) == 0:
                return "No regression runs found in the last {} days. Run some golden tests first.".format(days)

            lines = [
                f"## Regression Insights (last {days} days)\n",
                f"**Total runs**: {summary['total_runs']}  |  **Pass rate**: {(summary.get('pass_rate',0)*100):.1f}%",
                f"**Worst metric**: {summary.get('worst_metric', '—')}  |  **Most failed agent**: {summary.get('most_failed_agent', '—')}",
                "",
                "### Eval Metric Averages (lowest first)",
            ]
            for m in (data.get("worst_metrics") or [])[:8]:
                flag = "❌" if m.get("below_threshold", 0) > 0 else "✓"
                lines.append(
                    f"  {flag} **{m['metric']}**: avg={m['avg']}  threshold={m['threshold']}  "
                    f"below-threshold: {m.get('below_threshold', 0)}/{m.get('count', 0)}"
                )
            lines += ["", "### Most Expensive Tests"]
            for t in (data.get("costliest_tests") or [])[:5]:
                lines.append(f"  - {t['golden_case_id']}: avg=${t['avg_cost']:.5f}  avg_latency={t['avg_latency_ms']:.0f}ms  runs={t['runs']}")
            lines += ["", "### Failed Delegation Patterns (agent role → count)"]
            for agent, cnt in list((data.get("failed_agent_patterns") or {}).items())[:6]:
                lines.append(f"  - {agent}: {cnt} failed runs")
            return "\n".join(lines)
        except Exception as e:
            return f"Error fetching regression insights: {e}"

    return [
        StructuredTool.from_function(
            func=_run_sql,
            name="run_sql",
            description=(
                "Execute a read-only SELECT SQL query against the agent metrics database. "
                "Tables: regression_results, eval_runs, traces, spans, golden_test_cases, "
                "agents, teams. Always show the SQL query you ran in your response. "
                "Only SELECT statements are permitted."
            ),
            args_schema=RunSqlArgs,
        ),
        StructuredTool.from_function(
            func=_get_regression_insights,
            name="get_regression_insights",
            description=(
                "Get a structured summary of regression test performance: worst-scoring "
                "evaluation metrics (faithfulness, answer_relevancy, G-Eval scores), "
                "most expensive and slowest golden tests, agent roles in failed runs, "
                "and pass rates per test. Use this as a starting point before running "
                "custom SQL queries for deeper exploration."
            ),
            args_schema=RegressionInsightsArgs,
        ),
    ]


# ── Prompt Optimization tools (PromptOptimizer Agent) ─────────────────────────

def get_prompt_optimization_tools() -> list[StructuredTool]:
    """
    Tools for the PromptOptimizer meta-agent.

    Provides a complete self-improvement loop:
      1. get_regression_failures   — identify what's failing
      2. retrieve_similar_failures — get few-shot memory from past failures
      3. get_current_prompt        — read the prompt to improve
      4. register_prompt_version   — write improved version to registry
      5. diff_prompts              — show what changed
      6. run_regression_subset     — validate improvement on target tests
    """

    # ── Tool 1: get_regression_failures ───────────────────────────────────────

    class RegressionFailuresArgs(BaseModel):
        role: str = Field(description="Agent role to filter on (e.g. 'coder', 'planner').")
        metric: str = Field(
            default="step_efficiency",
            description="Metric to filter by (e.g. 'step_efficiency', 'tool_usage', 'correctness').",
        )
        threshold: float = Field(
            default=0.7,
            description="Score threshold — runs below this are returned as failures.",
        )
        version: str = Field(
            default="v1",
            description="Prompt version to analyse (e.g. 'v1', 'v2').",
        )
        run_id: Optional[str] = Field(
            default=None,
            description=(
                "Optional regression run_id to pin the baseline. If set, only "
                "failures from that specific run are returned (deterministic "
                "baseline). If omitted, scans all historical runs for the role."
            ),
        )
        limit: int = Field(default=20, description="Max results to return.")

    def _get_regression_failures(
        role: str,
        metric: str = "step_efficiency",
        threshold: float = 0.7,
        version: str = "v1",
        run_id: Optional[str] = None,
        limit: int = 20,
    ) -> str:
        """
        Return failing regression runs for an agent role filtered by a metric threshold.
        Shows golden test ID, metric score, tool calls used, and failure patterns.
        Use this to understand WHAT is failing and WHY before generating a prompt fix.
        """
        try:
            from src.db.database import get_session
            from sqlalchemy import text
            session = get_session()
            try:
                sql = """SELECT golden_case_id, golden_case_name, actual_agent,
                                quality_scores, deepeval_scores, actual_tool_calls,
                                actual_latency_ms, overall_pass, created_at
                         FROM regression_results
                         WHERE actual_agent LIKE :role
                           AND prompt_version = :version
                           AND overall_pass = 0"""
                params: dict = {"role": f"%{role}%", "version": version, "lim": limit}
                if run_id:
                    sql += " AND run_id = :run_id"
                    params["run_id"] = run_id
                sql += " ORDER BY created_at DESC LIMIT :lim"
                rows = session.execute(text(sql), params).fetchall()
            finally:
                session.close()

            if not rows:
                return (
                    f"No failing runs found for role={role} version={version}. "
                    "Either all tests passed or no data exists for this version yet."
                )

            import json as _json
            lines = [
                f"Failing regression runs — role={role} version={version} "
                f"metric={metric} threshold={threshold} ({len(rows)} found):\n"
            ]
            for r in rows:
                try:
                    qs = _json.loads(r[3]) if isinstance(r[3], str) else (r[3] or {})
                    ds = _json.loads(r[4]) if isinstance(r[4], str) else (r[4] or {})
                except Exception:
                    qs, ds = {}, {}

                score = qs.get(metric) or ds.get(metric)
                score_str = f"{score:.3f}" if score is not None else "N/A"
                lines.append(
                    f"  [{r[0]}] {r[1] or ''} | {metric}={score_str} "
                    f"| tool_calls={r[5]} | latency={int(r[6] or 0)}ms"
                )
                # Show all sub-threshold metrics
                all_scores = {**qs, **ds}
                bad = [f"{k}={v:.2f}" for k, v in all_scores.items()
                       if v is not None and isinstance(v, (int, float)) and v < threshold]
                if bad:
                    lines.append(f"    low metrics: {', '.join(bad)}")

            return "\n".join(lines)
        except Exception as e:
            return f"Error fetching regression failures: {e}"

    # ── Tool 2: retrieve_similar_failures ─────────────────────────────────────

    class SimilarFailuresArgs(BaseModel):
        role: str = Field(description="Agent role to search failures for.")
        query_text: str = Field(
            description=(
                "Natural-language description of the current failure pattern. "
                "E.g. 'coder writes file without reading first, low step_efficiency'"
            )
        )
        limit: int = Field(default=5, description="Max results to return.")

    def _retrieve_similar_failures(role: str, query_text: str, limit: int = 5) -> str:
        """
        Search the FeedbackStore for past failures similar to the current one.
        Returns tool traces, metric scores, and failure types from similar past runs.
        Use this as few-shot memory when drafting a prompt improvement.
        """
        try:
            from src.optimization.feedback_store import get_feedback_store
            store = get_feedback_store()
            results = store.retrieve_similar_failures(role, query_text, limit=limit)
            if not results:
                return f"No similar past failures found for role={role}. This may be the first optimization run."

            lines = [f"Similar past failures for role={role} ({len(results)} found):\n"]
            for fb in results:
                scores = ", ".join(
                    f"{k}={v:.2f}" for k, v in fb["quality_scores"].items()
                    if v is not None
                )
                lines.append(
                    f"  [{fb['golden_id']}] v={fb['version']} "
                    f"tools={fb['tool_trace_summary']} "
                    f"failures={fb['failure_types']} scores=[{scores}]"
                )
            return "\n".join(lines)
        except Exception as e:
            return f"Error retrieving similar failures: {e}"

    # ── Tool 3: get_current_prompt ─────────────────────────────────────────────

    class GetCurrentPromptArgs(BaseModel):
        role: str = Field(description="Agent role whose prompt to fetch.")
        version: str = Field(
            default="latest",
            description="Version to fetch: 'latest', 'v1', 'v2', etc.",
        )

    def _get_current_prompt(role: str, version: str = "latest") -> str:
        """
        Return the full system prompt for an agent role and version.
        Read this before writing an improved version so you can make targeted edits.
        """
        try:
            from src.prompts.registry import get_registry
            reg = get_registry()
            prompt = reg.get_prompt(role, version)
            if not prompt:
                return f"No prompt found for role={role} version={version}."
            actual_version = reg.latest_version(role) if version == "latest" else version
            return f"=== Prompt for role={role} version={actual_version} ===\n\n{prompt}"
        except Exception as e:
            return f"Error fetching prompt: {e}"

    # ── Tool 4: register_prompt_version ───────────────────────────────────────

    class RegisterPromptArgs(BaseModel):
        role: str = Field(description="Agent role this prompt is for.")
        new_prompt: str = Field(description="The full improved system prompt text.")
        rationale: str = Field(
            description=(
                "Explanation of what was changed and why. "
                "Be specific: e.g. 'Added explicit read-before-write constraint to fix "
                "low faithfulness caused by coder inventing file content without reading first.'"
            )
        )
        parent_version: Optional[str] = Field(
            default=None,
            description="The version this prompt was derived from (e.g. 'v1').",
        )

    def _register_prompt_version(
        role: str,
        new_prompt: str,
        rationale: str,
        parent_version: Optional[str] = None,
    ) -> str:
        """
        Register a new prompt version for an agent role in the PromptRegistry.
        Returns the new version label (e.g. 'v3'). The new version is immediately active.

        IMPORTANT: Only call this after you have:
          1. Read the current prompt with get_current_prompt
          2. Identified specific failure patterns with get_regression_failures
          3. Drafted a targeted improvement addressing those patterns
        """
        try:
            from src.prompts.registry import get_registry
            reg = get_registry()
            new_version = reg.register(
                role=role,
                prompt_text=new_prompt,
                rationale=rationale,
                parent_version=parent_version,
                created_by="optimizer",
                cot_enhanced="REASONING PROTOCOL" in new_prompt,
            )
            # Also update the Agent row in DB to reflect the new active version
            try:
                from src.db.database import get_session
                from src.db.models import Agent
                session = get_session()
                try:
                    agents = session.query(Agent).filter_by(role=role).all()
                    for a in agents:
                        a.prompt_version = new_version
                        a.system_prompt = new_prompt
                    session.commit()
                finally:
                    session.close()
            except Exception:
                pass  # DB update best-effort; registry is the source of truth
            return (
                f"✓ Registered {role} prompt as {new_version}. "
                f"Rationale: {rationale[:200]}... "
                f"Run run_regression_subset to validate improvement."
            )
        except Exception as e:
            return f"Error registering prompt: {e}"

    # ── Tool 5: diff_prompts ───────────────────────────────────────────────────

    class DiffPromptsArgs(BaseModel):
        role: str = Field(description="Agent role.")
        version_old: str = Field(description="Old version label (e.g. 'v1').")
        version_new: str = Field(description="New version label (e.g. 'v2').")

    def _diff_prompts(role: str, version_old: str, version_new: str) -> str:
        """
        Show a line-level diff between two prompt versions for a role.
        Use this to verify your changes are targeted and don't introduce regressions.
        """
        try:
            import difflib
            from src.prompts.registry import get_registry
            reg = get_registry()
            old_p = reg.get_prompt(role, version_old) or ""
            new_p = reg.get_prompt(role, version_new) or ""
            if not old_p:
                return f"Version {version_old} not found for role={role}."
            if not new_p:
                return f"Version {version_new} not found for role={role}."

            diff = list(difflib.unified_diff(
                old_p.splitlines(keepends=True),
                new_p.splitlines(keepends=True),
                fromfile=f"{role}/{version_old}",
                tofile=f"{role}/{version_new}",
                n=3,
            ))
            if not diff:
                return "Prompts are identical."
            # Limit output
            diff_text = "".join(diff[:120])
            if len(diff) > 120:
                diff_text += f"\n… ({len(diff) - 120} more lines)"
            return f"Diff {role} {version_old}→{version_new}:\n\n```diff\n{diff_text}\n```"
        except Exception as e:
            return f"Error computing diff: {e}"

    # ── Tool 6: run_regression_subset ─────────────────────────────────────────

    class RunRegressionSubsetArgs(BaseModel):
        role: str = Field(description="Agent role to test (used for logging only).")
        prompt_version: str = Field(
            description="Prompt version to use (e.g. 'v2'). Must be registered first."
        )
        golden_ids: list = Field(
            description="List of golden test case IDs to run (e.g. ['golden_004', 'golden_013'])."
        )
        model: str = Field(
            default="claude-sonnet-4.6",
            description="LLM model to use for this regression subset.",
        )
        team_id: str = Field(
            default="default",
            description=(
                "Team to run against ('default', 'sdlc_2_0', …). Pass the team "
                "the baseline was collected on so results are directly comparable."
            ),
        )
        max_parallel: int = Field(
            default=3,
            description="How many cases to run concurrently (1 = serial).",
        )

    def _run_regression_subset(
        role: str,
        prompt_version: str,
        golden_ids: list,
        model: str = "claude-sonnet-4.6",
        team_id: str = "default",
        max_parallel: int = 3,
    ) -> str:
        """
        Run a focused regression subset on specific golden tests with a given prompt version.
        Returns a pass/fail summary and metric scores for each test.
        Use this AFTER registering a new prompt version to validate improvement.
        Runs synchronously — may take 60-300s depending on test complexity.
        """
        try:
            import asyncio
            from src.evaluation.regression import RegressionRunner

            if not golden_ids:
                return "ERROR: golden_ids list is empty — specify at least one test to run."

            runner = RegressionRunner(
                model=model,
                team_id=team_id,
                prompt_version=prompt_version,
            )

            async def _run():
                return await runner.run_subset(golden_ids, max_parallel=max_parallel)

            try:
                loop = asyncio.get_event_loop()
                if loop.is_running():
                    import concurrent.futures
                    with concurrent.futures.ThreadPoolExecutor() as pool:
                        future = pool.submit(asyncio.run, _run())
                        results = future.result(timeout=600)
                else:
                    results = loop.run_until_complete(_run())
            except RuntimeError:
                results = asyncio.run(_run())

            if not results:
                return "Regression subset returned no results — check golden_ids are valid."

            lines = [
                f"Regression subset — role={role} version={prompt_version} "
                f"model={model} team={team_id} parallel={max_parallel} "
                f"({len(results)} tests):\n"
            ]
            passed = sum(1 for r in results if r.get("overall_pass"))
            lines.append(f"  Pass rate: {passed}/{len(results)}\n")
            for r in results:
                status = "✓" if r.get("overall_pass") else "✗"
                qs = r.get("quality_scores") or {}
                scores = ", ".join(
                    f"{k}={v:.2f}" for k, v in qs.items() if v is not None
                )
                lines.append(
                    f"  {status} [{r.get('golden_case_id', '?')}] {scores}"
                )
            return "\n".join(lines)
        except Exception as e:
            return f"Error running regression subset: {e}"

    # ── Tool 7: get_version_scores ─────────────────────────────────────────────

    class GetVersionScoresArgs(BaseModel):
        role: str = Field(description="Agent role (e.g. 'coder').")
        version: str = Field(
            default="latest",
            description="Prompt version to look up (e.g. 'v1', 'v2', 'latest').",
        )
        golden_ids: list = Field(
            default=[],
            description=(
                "Optional list of golden test IDs to filter on. "
                "Leave empty to aggregate all tests for this version."
            ),
        )

    def _get_version_scores(role: str, version: str = "latest", golden_ids: list = []) -> str:
        """
        Return aggregate metric scores + pass rate for a prompt version from regression history.
        Does NOT run new tests — reads stored results. Fast (instant).
        Use to compare before/after versions to decide whether to iterate again.
        """
        try:
            from src.db.database import get_session
            from sqlalchemy import text
            session = get_session()
            try:
                if version == "latest":
                    # Resolve latest version from registry
                    try:
                        from src.prompts.registry import get_registry
                        version = get_registry().latest_version(role)
                    except Exception:
                        version = "v1"

                params: dict = {"role": f"%{role}%", "version": version}
                filter_ids = ""
                if golden_ids:
                    placeholders = ",".join(f":id{i}" for i in range(len(golden_ids)))
                    filter_ids = f"AND golden_case_id IN ({placeholders})"
                    for i, gid in enumerate(golden_ids):
                        params[f"id{i}"] = gid

                rows = session.execute(text(f"""
                    SELECT golden_case_id, overall_pass, quality_scores, deepeval_scores,
                           actual_latency_ms, actual_cost
                    FROM regression_results
                    WHERE actual_agent LIKE :role
                      AND prompt_version = :version
                      {filter_ids}
                    ORDER BY created_at DESC
                """), params).fetchall()
            finally:
                session.close()

            if not rows:
                return (
                    f"No regression data found for role={role} version={version}. "
                    "Run run_regression_subset first to generate data."
                )

            import json as _json
            # Aggregate scores across all rows
            metric_sums: dict[str, list] = {}
            pass_count = 0
            total = len(rows)
            total_cost = 0.0
            total_latency = 0.0
            per_test: dict[str, dict] = {}

            for r in rows:
                gid = r[0]
                if gid in per_test:
                    continue  # take most recent per test
                per_test[gid] = {"pass": bool(r[1])}
                if r[1]:
                    pass_count += 1
                total_cost += r[5] or 0.0
                total_latency += r[4] or 0.0

                for scores_json in [r[2], r[3]]:
                    try:
                        scores = _json.loads(scores_json) if isinstance(scores_json, str) else (scores_json or {})
                        for m, v in scores.items():
                            if isinstance(v, (int, float)):
                                metric_sums.setdefault(m, []).append(v)
                    except Exception:
                        pass

            unique_tests = len(per_test)
            pass_rate = pass_count / unique_tests if unique_tests else 0.0
            avg_cost = total_cost / unique_tests if unique_tests else 0.0
            avg_latency = total_latency / unique_tests if unique_tests else 0.0

            lines = [
                f"Scores for role={role} version={version} "
                f"({unique_tests} unique tests in DB):\n",
                f"  Pass rate:   {pass_rate*100:.1f}%  ({pass_count}/{unique_tests})",
                f"  Avg cost:    ${avg_cost:.5f}",
                f"  Avg latency: {avg_latency/1000:.1f}s\n",
                "  Metric averages:",
            ]
            for m, vals in sorted(metric_sums.items()):
                avg = sum(vals) / len(vals)
                lines.append(f"    {m}: {avg:.3f}  (n={len(vals)})")

            lines.append("\n  Per-test pass/fail:")
            for gid, d in sorted(per_test.items()):
                status = "✓" if d["pass"] else "✗"
                lines.append(f"    {status} {gid}")

            return "\n".join(lines)
        except Exception as e:
            return f"Error fetching version scores: {e}"

    return [
        StructuredTool(
            func=_get_regression_failures,
            name="get_regression_failures",
            description=(
                "Get failing regression runs for an agent role filtered by a metric and threshold. "
                "Returns golden test ID, metric scores, tool call counts, and failure patterns. "
                "START HERE when asked to optimize a prompt."
            ),
            args_schema=RegressionFailuresArgs,
        ),
        StructuredTool(
            func=_retrieve_similar_failures,
            name="retrieve_similar_failures",
            description=(
                "Search the FeedbackStore for past failures similar to the current one. "
                "Returns tool traces, metric scores, and failure types from semantically "
                "similar past runs. Use as few-shot memory when drafting a prompt improvement."
            ),
            args_schema=SimilarFailuresArgs,
        ),
        StructuredTool(
            func=_get_current_prompt,
            name="get_current_prompt",
            description=(
                "Return the full system prompt for an agent role and version. "
                "Read this before writing an improved version to make targeted edits."
            ),
            args_schema=GetCurrentPromptArgs,
        ),
        StructuredTool(
            func=_register_prompt_version,
            name="register_prompt_version",
            description=(
                "Register a new prompt version for an agent role. "
                "The new version is immediately active. Requires: role, full prompt text, "
                "and a rationale explaining what changed and why. "
                "HITL checkpoint fires before this tool runs in non-regression mode."
            ),
            args_schema=RegisterPromptArgs,
        ),
        StructuredTool(
            func=_diff_prompts,
            name="diff_prompts",
            description=(
                "Show a unified diff between two prompt versions for a role. "
                "Use to verify changes are targeted and don't introduce regressions."
            ),
            args_schema=DiffPromptsArgs,
        ),
        StructuredTool(
            func=_run_regression_subset,
            name="run_regression_subset",
            description=(
                "Run a focused regression on specific golden tests with a given prompt version. "
                "Use AFTER register_prompt_version to validate improvement. "
                "Runs synchronously (60-300s). Returns pass/fail + metric scores per test."
            ),
            args_schema=RunRegressionSubsetArgs,
        ),
        StructuredTool(
            func=_get_version_scores,
            name="get_version_scores",
            description=(
                "Return aggregate metric scores and pass rate for a prompt version from the "
                "regression history — without re-running tests. Use this to compare two versions "
                "quickly (e.g. baseline v1 vs improved v3) to decide whether to iterate again."
            ),
            args_schema=GetVersionScoresArgs,
        ),
    ]
